n1 = int (input('Digite o primeiro número:' ))
n2 = int (input('Digite o segundo número: '))
soma = n1 + n2
sub = n1 - n2
div = n1 / n2
mult = n1 * n2 
print('A soma de', n1, '+',n2, 'é = ', soma)
print('A subtração de', n1, '-',n2, 'é = ', sub)
print('A divição de', n1, '/',n2, 'é = ', div)
print('A multiplicação de', n1, '*',n2, 'é = ', mult) 